"""fix foreign key for AttendanceTemporary

Revision ID: 053e0faf9926
Revises: 7f991e783000
Create Date: 2025-08-19 15:28:16.360538

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '053e0faf9926'
down_revision: Union[str, Sequence[str], None] = '7f991e783000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('id_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('batch', sa.String(), nullable=True))
    op.add_column('users', sa.Column('branch', sa.String(), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(), nullable=True))
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('users', 'gender')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'branch')
    op.drop_column('users', 'batch')
    op.drop_column('users', 'id_number')
    # ### end Alembic commands ###
