"""Add is_verified column to users

Revision ID: 46aaa1c819a9
Revises: be7d24f5d97d
Create Date: 2025-08-04 15:40:42.409251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46aaa1c819a9'
down_revision: Union[str, Sequence[str], None] = 'be7d24f5d97d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('email_notifications', 'body',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('email_notifications', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_verified')
    op.alter_column('email_notifications', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('email_notifications', 'body',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    # ### end Alembic commands ###
